import { Inter, Pacifico } from "next/font/google";
import "./globals.css";

const pacifico = Pacifico({ weight: "400", variable: "--font-pacifico" });
const inter = Inter({ subsets: ["lating"], variable: "--font-inter" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="autumn" className="scroll-smooth">
      <body className={`${inter.variable} ${pacifico.variable}`}>
        {children}
      </body>
    </html>
  );
}
